version: "3.8"

services:
  mysql:
    container_name: mysql-8
    image: mysql:8.0.29
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --default-time-zone=Asia/Singapore --sql-mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=root

